basemap:
  public: true
  formats: [pbf]
  uri: cassandra://
  params:
    maxzoom: 14 # Note: this max zoom is inclusive
    keyspace: basemap
    cp: {env: KARTOTHERIAN_CASSANDRA_SERVERS}
    username: {env: KARTOTHERIAN_CASSANDRA_USER}
    password: {env: KARTOTHERIAN_CASSANDRA_PSWD}
    createIfMissing: false
    setLastModified: true

ozbasemap:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: basemap}
  defaultHeaders:
    Cache-Control: 'public, max-age=43200, s-maxage=43200'
