gen:
  uri: https://maps.wikimedia.org/osm-pbf/{z}/{x}/{y}.pbf
  setInfo:
    vector_layers:
      - id: landuse
      - id: waterway
      - id: water
      - id: aeroway
      - id: building
      - id: road
      - id: admin
      - id: country_label
      - id: place_label
      - id: poi_label
      - id: road_label

# View tiles as generated directly from the database. Don't view zoom0-5
osm-intl:
  public: true
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: tmstyle://
  yaml:
    npm: ["@kartotherian/osm-bright-style", "project.yml"]
  yamlSetParams:
    source: {ref: gen}



# Generates vtiles from database
### Basemap
gen_basemap:
  public: true
  formats: [pbf]
  uri: tmsource://
  yaml: "/etc/tilerator/data_tm2source_base.yml"
  yamlSetDataSource:
    set:
      type: postgis
      dbname: gis
      host: {env: TILERATOR_OSMDB_HOST}
      user: {env: TILERATOR_OSMDB_USER}
      password: {env: TILERATOR_OSMDB_PSWD}

basemap:
  public: true
  formats: [pbf]
  uri: cassandra://
  params:
    maxzoom: 15
    keyspace: basemap
    cp: {env: TILERATOR_CASSANDRA_SERVERS}
    username: {env: TILERATOR_CASSANDRA_USER}
    password: {env: TILERATOR_CASSANDRA_PSWD}
    repfactor: 4
    durablewrite: 0
    createIfMissing: true
    copyInfoFrom: {ref: gen_basemap}

substbasemap:  # only for basemap
  public: true
  formats: [pbf]
  uri: substantial://
  params:
    source: {ref: gen_basemap}
    minzoom: 10
    maxsize: 100
    layers: [water, landuse, landcover]
